import ProfileHeader from "../../components/profile-header";
import RankedDisplay from "../../components/ranked-display";
import MatchDisplay from "../../components/match-display";
import {Card, CardHeader, CardBody, CardFooter} from "@heroui/card";

const summonerInfo = {
  "tagLine": "NA1",
  "lp": 87,
  "tier": "DIAMOND",
  "profileIconId": 6853,
  "summonerLevel": 1042,
  "hotStreak": true,
  "matches": [
      {
          "blueTeam": {
              "stats": {
                  "inhibitors": 0,
                  "totalKills": 26,
                  "totalGold": 33077,
                  "barons": 0,
                  "voidGrubs": 3,
                  "riftHeralds": 0,
                  "win": true,
                  "searchedPlayer": true,
                  "dragons": 1,
                  "atakhan": 0,
                  "towers": 3
              },
              "participants": [
                  {
                      "kills": 5,
                      "item0": 1056,
                      "item2": 3108,
                      "role": "TOP",
                      "item1": 3158,
                      "csPerMin": 6.8,
                      "multikill": "None",
                      "champLevel": 12,
                      "assists": 1,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8000,
                      "win": true,
                      "deaths": 2,
                      "damageDealt": 13421,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 79,
                      "pinkWards": 1,
                      "summonerSpell2": 4,
                      "summonerSpell1": 12,
                      "summonerName": "White Rose",
                      "kda": 3,
                      "cs": 103,
                      "championName": "Gragas",
                      "wardsPlaced": 6,
                      "keystoneRune": 8230,
                      "wardItem": 3340,
                      "item4": 1052,
                      "item3": 6657,
                      "damageTaken": 14137,
                      "item5": 0
                  },
                  {
                      "kills": 7,
                      "item0": 1102,
                      "item2": 0,
                      "role": "JUNGLE",
                      "item1": 6672,
                      "csPerMin": 7.6,
                      "multikill": "Double Kill",
                      "champLevel": 11,
                      "assists": 4,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8100,
                      "win": true,
                      "deaths": 0,
                      "damageDealt": 6531,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 200,
                      "pinkWards": 0,
                      "summonerSpell2": 11,
                      "summonerSpell1": 4,
                      "summonerName": "Miko",
                      "kda": 999,
                      "cs": 116,
                      "championName": "Belveth",
                      "wardsPlaced": 1,
                      "keystoneRune": 8010,
                      "wardItem": 3364,
                      "item4": 1036,
                      "item3": 1001,
                      "damageTaken": 12620,
                      "item5": 3077
                  },
                  {
                      "kills": 6,
                      "item0": 6657,
                      "item2": 3020,
                      "role": "MIDDLE",
                      "item1": 1056,
                      "csPerMin": 6.1,
                      "multikill": "None",
                      "champLevel": 11,
                      "assists": 5,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8200,
                      "win": true,
                      "deaths": 1,
                      "damageDealt": 9910,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 103,
                      "pinkWards": 0,
                      "summonerSpell2": 12,
                      "summonerSpell1": 4,
                      "summonerName": "Nuclear Gandhî",
                      "kda": 11,
                      "cs": 93,
                      "championName": "Ahri",
                      "wardsPlaced": 6,
                      "keystoneRune": 8112,
                      "wardItem": 3364,
                      "item4": 2508,
                      "item3": 3147,
                      "damageTaken": 8101,
                      "item5": 0
                  },
                  {
                      "kills": 5,
                      "item0": 1055,
                      "item2": 6676,
                      "role": "BOTTOM",
                      "item1": 3009,
                      "csPerMin": 7.2,
                      "multikill": "Double Kill",
                      "champLevel": 9,
                      "assists": 6,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8000,
                      "win": true,
                      "deaths": 0,
                      "damageDealt": 8848,
                      "searchedPlayer": false,
                      "wardsKilled": 1,
                      "championID": 202,
                      "pinkWards": 2,
                      "summonerSpell2": 4,
                      "summonerSpell1": 21,
                      "summonerName": "ShadowshinesV2",
                      "kda": 999,
                      "cs": 110,
                      "championName": "Jhin",
                      "wardsPlaced": 7,
                      "keystoneRune": 8229,
                      "wardItem": 3340,
                      "item4": 1038,
                      "item3": 1042,
                      "damageTaken": 4199,
                      "item5": 1037
                  },
                  {
                      "kills": 3,
                      "item0": 3877,
                      "item2": 1037,
                      "role": "UTILITY",
                      "item1": 1036,
                      "csPerMin": 1.1,
                      "multikill": "None",
                      "champLevel": 8,
                      "assists": 10,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8400,
                      "win": true,
                      "deaths": 1,
                      "damageDealt": 7108,
                      "searchedPlayer": true,
                      "wardsKilled": 1,
                      "championID": 555,
                      "pinkWards": 0,
                      "summonerSpell2": 14,
                      "summonerSpell1": 4,
                      "summonerName": "Anc702",
                      "kda": 13,
                      "cs": 16,
                      "championName": "Pyke",
                      "wardsPlaced": 7,
                      "keystoneRune": 9923,
                      "wardItem": 3340,
                      "item4": 3010,
                      "item3": 0,
                      "damageTaken": 8659,
                      "item5": 3179
                  }
              ]
          },
          "matchData": {
              "gameDurationMinutes": 15,
              "gameType": "MATCHED_GAME",
              "gameDurationSeconds": 13,
              "gameMode": "CLASSIC",
              "totalGameDuration": 913
          },
          "redTeam": {
              "stats": {
                  "inhibitors": 0,
                  "totalKills": 4,
                  "totalGold": 21996,
                  "barons": 0,
                  "voidGrubs": 0,
                  "riftHeralds": 0,
                  "win": false,
                  "searchedPlayer": false,
                  "dragons": 0,
                  "atakhan": 0,
                  "towers": 0
              },
              "participants": [
                  {
                      "kills": 0,
                      "item0": 3133,
                      "item2": 2031,
                      "role": "TOP",
                      "item1": 1036,
                      "csPerMin": 6.6,
                      "multikill": "None",
                      "champLevel": 10,
                      "assists": 0,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8400,
                      "win": false,
                      "deaths": 5,
                      "damageDealt": 10758,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 266,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 12,
                      "summonerName": "old and slow",
                      "kda": 0,
                      "cs": 101,
                      "championName": "Aatrox",
                      "wardsPlaced": 4,
                      "keystoneRune": 8010,
                      "wardItem": 3363,
                      "item4": 3111,
                      "item3": 1054,
                      "damageTaken": 16171,
                      "item5": 1037
                  },
                  {
                      "kills": 0,
                      "item0": 1102,
                      "item2": 0,
                      "role": "JUNGLE",
                      "item1": 6676,
                      "csPerMin": 4.2,
                      "multikill": "None",
                      "champLevel": 8,
                      "assists": 1,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8100,
                      "win": false,
                      "deaths": 7,
                      "damageDealt": 2943,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 203,
                      "pinkWards": 0,
                      "summonerSpell2": 11,
                      "summonerSpell1": 4,
                      "summonerName": "WxXuehua86868668",
                      "kda": 0.14,
                      "cs": 64,
                      "championName": "Kindred",
                      "wardsPlaced": 1,
                      "keystoneRune": 8005,
                      "wardItem": 3364,
                      "item4": 0,
                      "item3": 0,
                      "damageTaken": 12828,
                      "item5": 0
                  },
                  {
                      "kills": 3,
                      "item0": 1054,
                      "item2": 1001,
                      "role": "MIDDLE",
                      "item1": 4646,
                      "csPerMin": 6.5,
                      "multikill": "None",
                      "champLevel": 11,
                      "assists": 0,
                      "killParticipation": 1,
                      "teamID": 200,
                      "secondaryTree": 8400,
                      "win": false,
                      "deaths": 4,
                      "damageDealt": 7841,
                      "searchedPlayer": false,
                      "wardsKilled": 1,
                      "championID": 84,
                      "pinkWards": 0,
                      "summonerSpell2": 12,
                      "summonerSpell1": 4,
                      "summonerName": "MapleTheCat",
                      "kda": 0.75,
                      "cs": 99,
                      "championName": "Akali",
                      "wardsPlaced": 5,
                      "keystoneRune": 8021,
                      "wardItem": 3340,
                      "item4": 3145,
                      "item3": 1058,
                      "damageTaken": 11301,
                      "item5": 0
                  },
                  {
                      "kills": 0,
                      "item0": 1055,
                      "item2": 1001,
                      "role": "BOTTOM",
                      "item1": 3508,
                      "csPerMin": 6,
                      "multikill": "None",
                      "champLevel": 8,
                      "assists": 1,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8200,
                      "win": false,
                      "deaths": 5,
                      "damageDealt": 5238,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 901,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 21,
                      "summonerName": "Yumi 0v0",
                      "kda": 0.2,
                      "cs": 92,
                      "championName": "Smolder",
                      "wardsPlaced": 4,
                      "keystoneRune": 8021,
                      "wardItem": 3340,
                      "item4": 0,
                      "item3": 0,
                      "damageTaken": 8132,
                      "item5": 0
                  },
                  {
                      "kills": 0,
                      "item0": 2003,
                      "item2": 3866,
                      "role": "UTILITY",
                      "item1": 1001,
                      "csPerMin": 1.3,
                      "multikill": "None",
                      "champLevel": 8,
                      "assists": 0,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8100,
                      "win": false,
                      "deaths": 5,
                      "damageDealt": 4239,
                      "searchedPlayer": false,
                      "wardsKilled": 1,
                      "championID": 143,
                      "pinkWards": 1,
                      "summonerSpell2": 14,
                      "summonerSpell1": 4,
                      "summonerName": "Ghoul",
                      "kda": 0,
                      "cs": 20,
                      "championName": "Zyra",
                      "wardsPlaced": 10,
                      "keystoneRune": 8229,
                      "wardItem": 3364,
                      "item4": 2508,
                      "item3": 2022,
                      "damageTaken": 6876,
                      "item5": 1052
                  }
              ]
          }
      },
      {
          "blueTeam": {
              "stats": {
                  "inhibitors": 0,
                  "totalKills": 33,
                  "totalGold": 56361,
                  "barons": 0,
                  "voidGrubs": 0,
                  "riftHeralds": 1,
                  "win": false,
                  "searchedPlayer": false,
                  "dragons": 2,
                  "atakhan": 0,
                  "towers": 5
              },
              "participants": [
                  {
                      "kills": 2,
                      "item0": 1054,
                      "item2": 3009,
                      "role": "TOP",
                      "item1": 3078,
                      "csPerMin": 7,
                      "multikill": "None",
                      "champLevel": 15,
                      "assists": 6,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8200,
                      "win": false,
                      "deaths": 5,
                      "damageDealt": 11559,
                      "searchedPlayer": false,
                      "wardsKilled": 1,
                      "championID": 106,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 12,
                      "summonerName": "Womsky",
                      "kda": 1.6,
                      "cs": 193,
                      "championName": "Volibear",
                      "wardsPlaced": 7,
                      "keystoneRune": 8005,
                      "wardItem": 3363,
                      "item4": 3086,
                      "item3": 3181,
                      "damageTaken": 27321,
                      "item5": 1042
                  },
                  {
                      "kills": 6,
                      "item0": 6698,
                      "item2": 3035,
                      "role": "JUNGLE",
                      "item1": 3142,
                      "csPerMin": 6.8,
                      "multikill": "Double Kill",
                      "champLevel": 16,
                      "assists": 8,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8300,
                      "win": false,
                      "deaths": 8,
                      "damageDealt": 15376,
                      "searchedPlayer": false,
                      "wardsKilled": 2,
                      "championID": 91,
                      "pinkWards": 0,
                      "summonerSpell2": 11,
                      "summonerSpell1": 4,
                      "summonerName": "秋日无多丶",
                      "kda": 1.75,
                      "cs": 187,
                      "championName": "Talon",
                      "wardsPlaced": 0,
                      "keystoneRune": 8112,
                      "wardItem": 3364,
                      "item4": 6692,
                      "item3": 0,
                      "damageTaken": 35179,
                      "item5": 3158
                  },
                  {
                      "kills": 11,
                      "item0": 4633,
                      "item2": 6657,
                      "role": "MIDDLE",
                      "item1": 1052,
                      "csPerMin": 6.4,
                      "multikill": "Double Kill",
                      "champLevel": 16,
                      "assists": 5,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8200,
                      "win": false,
                      "deaths": 8,
                      "damageDealt": 27211,
                      "searchedPlayer": false,
                      "wardsKilled": 2,
                      "championID": 517,
                      "pinkWards": 1,
                      "summonerSpell2": 4,
                      "summonerSpell1": 12,
                      "summonerName": "한국 김치",
                      "kda": 2,
                      "cs": 176,
                      "championName": "Sylas",
                      "wardsPlaced": 5,
                      "keystoneRune": 8010,
                      "wardItem": 3364,
                      "item4": 4629,
                      "item3": 3158,
                      "damageTaken": 37032,
                      "item5": 1029
                  },
                  {
                      "kills": 14,
                      "item0": 3032,
                      "item2": 3006,
                      "role": "BOTTOM",
                      "item1": 6673,
                      "csPerMin": 7.9,
                      "multikill": "Double Kill",
                      "champLevel": 14,
                      "assists": 2,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8200,
                      "win": false,
                      "deaths": 5,
                      "damageDealt": 34837,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 51,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 21,
                      "summonerName": "ADC FUN ROLE",
                      "kda": 3.2,
                      "cs": 218,
                      "championName": "Caitlyn",
                      "wardsPlaced": 8,
                      "keystoneRune": 8008,
                      "wardItem": 3363,
                      "item4": 3036,
                      "item3": 3031,
                      "damageTaken": 17693,
                      "item5": 1042
                  },
                  {
                      "kills": 0,
                      "item0": 3876,
                      "item2": 3109,
                      "role": "UTILITY",
                      "item1": 3190,
                      "csPerMin": 0.5,
                      "multikill": "None",
                      "champLevel": 13,
                      "assists": 20,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8300,
                      "win": false,
                      "deaths": 5,
                      "damageDealt": 9760,
                      "searchedPlayer": false,
                      "wardsKilled": 3,
                      "championID": 201,
                      "pinkWards": 6,
                      "summonerSpell2": 3,
                      "summonerSpell1": 4,
                      "summonerName": "IIIlllIII",
                      "kda": 4,
                      "cs": 14,
                      "championName": "Braum",
                      "wardsPlaced": 30,
                      "keystoneRune": 8465,
                      "wardItem": 3364,
                      "item4": 1029,
                      "item3": 3047,
                      "damageTaken": 17716,
                      "item5": 1033
                  }
              ]
          },
          "matchData": {
              "gameDurationMinutes": 27,
              "gameType": "MATCHED_GAME",
              "gameDurationSeconds": 37,
              "gameMode": "CLASSIC",
              "totalGameDuration": 1657
          },
          "redTeam": {
              "stats": {
                  "inhibitors": 1,
                  "totalKills": 31,
                  "totalGold": 62022,
                  "barons": 1,
                  "voidGrubs": 3,
                  "riftHeralds": 0,
                  "win": true,
                  "searchedPlayer": true,
                  "dragons": 2,
                  "atakhan": 1,
                  "towers": 9
              },
              "participants": [
                  {
                      "kills": 3,
                      "item0": 1055,
                      "item2": 3174,
                      "role": "TOP",
                      "item1": 1037,
                      "csPerMin": 7.4,
                      "multikill": "None",
                      "champLevel": 16,
                      "assists": 8,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8400,
                      "win": true,
                      "deaths": 5,
                      "damageDealt": 24256,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 150,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 12,
                      "summonerName": "Moonslush",
                      "kda": 2.2,
                      "cs": 204,
                      "championName": "Gnar",
                      "wardsPlaced": 9,
                      "keystoneRune": 8021,
                      "wardItem": 3340,
                      "item4": 3071,
                      "item3": 3078,
                      "damageTaken": 26500,
                      "item5": 2021
                  },
                  {
                      "kills": 9,
                      "item0": 3091,
                      "item2": 0,
                      "role": "JUNGLE",
                      "item1": 1029,
                      "csPerMin": 7.1,
                      "multikill": "Double Kill",
                      "champLevel": 16,
                      "assists": 7,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8300,
                      "win": true,
                      "deaths": 5,
                      "damageDealt": 21614,
                      "searchedPlayer": false,
                      "wardsKilled": 2,
                      "championID": 11,
                      "pinkWards": 2,
                      "summonerSpell2": 11,
                      "summonerSpell1": 4,
                      "summonerName": "爱会冷掉",
                      "kda": 3.2,
                      "cs": 195,
                      "championName": "MasterYi",
                      "wardsPlaced": 12,
                      "keystoneRune": 8008,
                      "wardItem": 3340,
                      "item4": 3124,
                      "item3": 3174,
                      "damageTaken": 29148,
                      "item5": 3153
                  },
                  {
                      "kills": 13,
                      "item0": 3135,
                      "item2": 3157,
                      "role": "MIDDLE",
                      "item1": 3100,
                      "csPerMin": 7.4,
                      "multikill": "Double Kill",
                      "champLevel": 17,
                      "assists": 9,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8400,
                      "win": true,
                      "deaths": 9,
                      "damageDealt": 36975,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 131,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 12,
                      "summonerName": "Tøkai Teio",
                      "kda": 2.44,
                      "cs": 205,
                      "championName": "Diana",
                      "wardsPlaced": 7,
                      "keystoneRune": 8230,
                      "wardItem": 3340,
                      "item4": 4645,
                      "item3": 1082,
                      "damageTaken": 25141,
                      "item5": 3175
                  },
                  {
                      "kills": 5,
                      "item0": 3036,
                      "item2": 3111,
                      "role": "BOTTOM",
                      "item1": 0,
                      "csPerMin": 6.4,
                      "multikill": "Triple Kill",
                      "champLevel": 15,
                      "assists": 11,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8300,
                      "win": true,
                      "deaths": 8,
                      "damageDealt": 14664,
                      "searchedPlayer": true,
                      "wardsKilled": 1,
                      "championID": 895,
                      "pinkWards": 0,
                      "summonerSpell2": 6,
                      "summonerSpell1": 4,
                      "summonerName": "Anc702",
                      "kda": 2,
                      "cs": 178,
                      "championName": "Nilah",
                      "wardsPlaced": 8,
                      "keystoneRune": 8010,
                      "wardItem": 3363,
                      "item4": 6676,
                      "item3": 0,
                      "damageTaken": 25919,
                      "item5": 3031
                  },
                  {
                      "kills": 1,
                      "item0": 3876,
                      "item2": 3121,
                      "role": "UTILITY",
                      "item1": 3190,
                      "csPerMin": 1.4,
                      "multikill": "None",
                      "champLevel": 14,
                      "assists": 17,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8400,
                      "win": true,
                      "deaths": 6,
                      "damageDealt": 7732,
                      "searchedPlayer": false,
                      "wardsKilled": 7,
                      "championID": 44,
                      "pinkWards": 1,
                      "summonerSpell2": 4,
                      "summonerSpell1": 7,
                      "summonerName": "xepax",
                      "kda": 3,
                      "cs": 39,
                      "championName": "Taric",
                      "wardsPlaced": 17,
                      "keystoneRune": 8351,
                      "wardItem": 3364,
                      "item4": 0,
                      "item3": 3082,
                      "damageTaken": 28618,
                      "item5": 3009
                  }
              ]
          }
      },
      {
          "blueTeam": {
              "stats": {
                  "inhibitors": 2,
                  "totalKills": 26,
                  "totalGold": 52286,
                  "barons": 0,
                  "voidGrubs": 2,
                  "riftHeralds": 1,
                  "win": true,
                  "searchedPlayer": true,
                  "dragons": 4,
                  "atakhan": 1,
                  "towers": 10
              },
              "participants": [
                  {
                      "kills": 2,
                      "item0": 0,
                      "item2": 2022,
                      "role": "TOP",
                      "item1": 0,
                      "csPerMin": 7.9,
                      "multikill": "None",
                      "champLevel": 15,
                      "assists": 4,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8400,
                      "win": true,
                      "deaths": 4,
                      "damageDealt": 20692,
                      "searchedPlayer": true,
                      "wardsKilled": 2,
                      "championID": 68,
                      "pinkWards": 0,
                      "summonerSpell2": 12,
                      "summonerSpell1": 4,
                      "summonerName": "Anc702",
                      "kda": 1.5,
                      "cs": 195,
                      "championName": "Rumble",
                      "wardsPlaced": 8,
                      "keystoneRune": 8229,
                      "wardItem": 3340,
                      "item4": 6653,
                      "item3": 3175,
                      "damageTaken": 17295,
                      "item5": 8010
                  },
                  {
                      "kills": 2,
                      "item0": 3111,
                      "item2": 0,
                      "role": "JUNGLE",
                      "item1": 2031,
                      "csPerMin": 6.1,
                      "multikill": "None",
                      "champLevel": 14,
                      "assists": 11,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8300,
                      "win": true,
                      "deaths": 2,
                      "damageDealt": 10562,
                      "searchedPlayer": false,
                      "wardsKilled": 1,
                      "championID": 254,
                      "pinkWards": 2,
                      "summonerSpell2": 4,
                      "summonerSpell1": 11,
                      "summonerName": "end plz",
                      "kda": 6.5,
                      "cs": 151,
                      "championName": "Vi",
                      "wardsPlaced": 11,
                      "keystoneRune": 8010,
                      "wardItem": 3364,
                      "item4": 3071,
                      "item3": 6610,
                      "damageTaken": 23547,
                      "item5": 1028
                  },
                  {
                      "kills": 6,
                      "item0": 1054,
                      "item2": 6664,
                      "role": "MIDDLE",
                      "item1": 1082,
                      "csPerMin": 8.1,
                      "multikill": "Double Kill",
                      "champLevel": 15,
                      "assists": 9,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8000,
                      "win": true,
                      "deaths": 4,
                      "damageDealt": 19354,
                      "searchedPlayer": false,
                      "wardsKilled": 3,
                      "championID": 154,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 12,
                      "summonerName": "Yelich",
                      "kda": 3.75,
                      "cs": 202,
                      "championName": "Zac",
                      "wardsPlaced": 8,
                      "keystoneRune": 8439,
                      "wardItem": 3363,
                      "item4": 2502,
                      "item3": 3173,
                      "damageTaken": 32262,
                      "item5": 3082
                  },
                  {
                      "kills": 15,
                      "item0": 3072,
                      "item2": 3032,
                      "role": "BOTTOM",
                      "item1": 3006,
                      "csPerMin": 8.3,
                      "multikill": "Double Kill",
                      "champLevel": 14,
                      "assists": 5,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8200,
                      "win": true,
                      "deaths": 2,
                      "damageDealt": 35892,
                      "searchedPlayer": false,
                      "wardsKilled": 2,
                      "championID": 222,
                      "pinkWards": 1,
                      "summonerSpell2": 4,
                      "summonerSpell1": 21,
                      "summonerName": "Zen",
                      "kda": 10,
                      "cs": 205,
                      "championName": "Jinx",
                      "wardsPlaced": 8,
                      "keystoneRune": 8008,
                      "wardItem": 3363,
                      "item4": 0,
                      "item3": 3031,
                      "damageTaken": 13425,
                      "item5": 0
                  },
                  {
                      "kills": 1,
                      "item0": 3876,
                      "item2": 3109,
                      "role": "UTILITY",
                      "item1": 3190,
                      "csPerMin": 0.8,
                      "multikill": "None",
                      "champLevel": 13,
                      "assists": 19,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8000,
                      "win": true,
                      "deaths": 3,
                      "damageDealt": 7892,
                      "searchedPlayer": false,
                      "wardsKilled": 5,
                      "championID": 201,
                      "pinkWards": 3,
                      "summonerSpell2": 4,
                      "summonerSpell1": 7,
                      "summonerName": "xepax",
                      "kda": 6.67,
                      "cs": 21,
                      "championName": "Braum",
                      "wardsPlaced": 24,
                      "keystoneRune": 8465,
                      "wardItem": 3364,
                      "item4": 1029,
                      "item3": 3111,
                      "damageTaken": 19143,
                      "item5": 0
                  }
              ]
          },
          "matchData": {
              "gameDurationMinutes": 24,
              "gameType": "MATCHED_GAME",
              "gameDurationSeconds": 50,
              "gameMode": "CLASSIC",
              "totalGameDuration": 1490
          },
          "redTeam": {
              "stats": {
                  "inhibitors": 0,
                  "totalKills": 15,
                  "totalGold": 42696,
                  "barons": 0,
                  "voidGrubs": 1,
                  "riftHeralds": 0,
                  "win": false,
                  "searchedPlayer": false,
                  "dragons": 0,
                  "atakhan": 0,
                  "towers": 3
              },
              "participants": [
                  {
                      "kills": 2,
                      "item0": 1054,
                      "item2": 3047,
                      "role": "TOP",
                      "item1": 6664,
                      "csPerMin": 6.6,
                      "multikill": "None",
                      "champLevel": 14,
                      "assists": 3,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8000,
                      "win": false,
                      "deaths": 6,
                      "damageDealt": 14952,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 14,
                      "pinkWards": 3,
                      "summonerSpell2": 12,
                      "summonerSpell1": 4,
                      "summonerName": "ZeroSShark",
                      "kda": 0.83,
                      "cs": 163,
                      "championName": "Sion",
                      "wardsPlaced": 10,
                      "keystoneRune": 8437,
                      "wardItem": 3340,
                      "item4": 1028,
                      "item3": 3084,
                      "damageTaken": 38745,
                      "item5": 0
                  },
                  {
                      "kills": 1,
                      "item0": 6699,
                      "item2": 3158,
                      "role": "JUNGLE",
                      "item1": 6692,
                      "csPerMin": 6.5,
                      "multikill": "None",
                      "champLevel": 13,
                      "assists": 8,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8200,
                      "win": false,
                      "deaths": 2,
                      "damageDealt": 10866,
                      "searchedPlayer": false,
                      "wardsKilled": 5,
                      "championID": 238,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 11,
                      "summonerName": "wardy",
                      "kda": 4.5,
                      "cs": 162,
                      "championName": "Zed",
                      "wardsPlaced": 3,
                      "keystoneRune": 8010,
                      "wardItem": 3364,
                      "item4": 0,
                      "item3": 1036,
                      "damageTaken": 23155,
                      "item5": 0
                  },
                  {
                      "kills": 6,
                      "item0": 1056,
                      "item2": 1058,
                      "role": "MIDDLE",
                      "item1": 1058,
                      "csPerMin": 6.9,
                      "multikill": "None",
                      "champLevel": 14,
                      "assists": 5,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8200,
                      "win": false,
                      "deaths": 4,
                      "damageDealt": 25583,
                      "searchedPlayer": false,
                      "wardsKilled": 1,
                      "championID": 103,
                      "pinkWards": 1,
                      "summonerSpell2": 4,
                      "summonerSpell1": 12,
                      "summonerName": "Háki",
                      "kda": 2.75,
                      "cs": 171,
                      "championName": "Ahri",
                      "wardsPlaced": 8,
                      "keystoneRune": 8112,
                      "wardItem": 3364,
                      "item4": 4628,
                      "item3": 3020,
                      "damageTaken": 18173,
                      "item5": 3118
                  },
                  {
                      "kills": 2,
                      "item0": 3032,
                      "item2": 3031,
                      "role": "BOTTOM",
                      "item1": 3006,
                      "csPerMin": 8.4,
                      "multikill": "None",
                      "champLevel": 13,
                      "assists": 3,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8300,
                      "win": false,
                      "deaths": 6,
                      "damageDealt": 11508,
                      "searchedPlayer": false,
                      "wardsKilled": 6,
                      "championID": 18,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 21,
                      "summonerName": "diyisa",
                      "kda": 0.83,
                      "cs": 209,
                      "championName": "Tristana",
                      "wardsPlaced": 8,
                      "keystoneRune": 8008,
                      "wardItem": 3363,
                      "item4": 3035,
                      "item3": 1055,
                      "damageTaken": 17470,
                      "item5": 0
                  },
                  {
                      "kills": 4,
                      "item0": 4632,
                      "item2": 3876,
                      "role": "UTILITY",
                      "item1": 6655,
                      "csPerMin": 1.3,
                      "multikill": "None",
                      "champLevel": 11,
                      "assists": 4,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8000,
                      "win": false,
                      "deaths": 8,
                      "damageDealt": 11399,
                      "searchedPlayer": false,
                      "wardsKilled": 6,
                      "championID": 99,
                      "pinkWards": 1,
                      "summonerSpell2": 4,
                      "summonerSpell1": 7,
                      "summonerName": "Ari",
                      "kda": 1,
                      "cs": 32,
                      "championName": "Lux",
                      "wardsPlaced": 18,
                      "keystoneRune": 8229,
                      "wardItem": 3364,
                      "item4": 0,
                      "item3": 0,
                      "damageTaken": 17167,
                      "item5": 3020
                  }
              ]
          }
      },
      {
          "blueTeam": {
              "stats": {
                  "inhibitors": 0,
                  "totalKills": 0,
                  "totalGold": 2630,
                  "barons": 0,
                  "voidGrubs": 0,
                  "riftHeralds": 0,
                  "win": false,
                  "searchedPlayer": true,
                  "dragons": 0,
                  "atakhan": 0,
                  "towers": 0
              },
              "participants": [
                  {
                      "kills": 0,
                      "item0": 1054,
                      "item2": 0,
                      "role": "TOP",
                      "item1": 2003,
                      "csPerMin": 0,
                      "multikill": "None",
                      "champLevel": 1,
                      "assists": 0,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8000,
                      "win": false,
                      "deaths": 0,
                      "damageDealt": 0,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 154,
                      "pinkWards": 0,
                      "summonerSpell2": 12,
                      "summonerSpell1": 14,
                      "summonerName": "xepax",
                      "kda": 999,
                      "cs": 0,
                      "championName": "Zac",
                      "wardsPlaced": 0,
                      "keystoneRune": 8437,
                      "wardItem": 3340,
                      "item4": 0,
                      "item3": 0,
                      "damageTaken": 0,
                      "item5": 0
                  },
                  {
                      "kills": 0,
                      "item0": 1103,
                      "item2": 0,
                      "role": "JUNGLE",
                      "item1": 2003,
                      "csPerMin": 0,
                      "multikill": "None",
                      "champLevel": 1,
                      "assists": 0,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8300,
                      "win": false,
                      "deaths": 0,
                      "damageDealt": 61,
                      "searchedPlayer": true,
                      "wardsKilled": 0,
                      "championID": 59,
                      "pinkWards": 0,
                      "summonerSpell2": 11,
                      "summonerSpell1": 4,
                      "summonerName": "Anc702",
                      "kda": 999,
                      "cs": 0,
                      "championName": "JarvanIV",
                      "wardsPlaced": 0,
                      "keystoneRune": 8010,
                      "wardItem": 3364,
                      "item4": 0,
                      "item3": 0,
                      "damageTaken": 697,
                      "item5": 0
                  },
                  {
                      "kills": 0,
                      "item0": 0,
                      "item2": 0,
                      "role": "MIDDLE",
                      "item1": 0,
                      "csPerMin": 0,
                      "multikill": "None",
                      "champLevel": 1,
                      "assists": 0,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8100,
                      "win": false,
                      "deaths": 0,
                      "damageDealt": 0,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 1,
                      "pinkWards": 0,
                      "summonerSpell2": 12,
                      "summonerSpell1": 4,
                      "summonerName": "Dragouel",
                      "kda": 999,
                      "cs": 0,
                      "championName": "Annie",
                      "wardsPlaced": 0,
                      "keystoneRune": 8229,
                      "wardItem": 0,
                      "item4": 0,
                      "item3": 0,
                      "damageTaken": 0,
                      "item5": 0
                  },
                  {
                      "kills": 0,
                      "item0": 1055,
                      "item2": 2003,
                      "role": "BOTTOM",
                      "item1": 0,
                      "csPerMin": 0,
                      "multikill": "None",
                      "champLevel": 1,
                      "assists": 0,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8200,
                      "win": false,
                      "deaths": 1,
                      "damageDealt": 403,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 42,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 1,
                      "summonerName": "T1 Ruler",
                      "kda": 0,
                      "cs": 0,
                      "championName": "Corki",
                      "wardsPlaced": 0,
                      "keystoneRune": 8010,
                      "wardItem": 3340,
                      "item4": 0,
                      "item3": 0,
                      "damageTaken": 735,
                      "item5": 0
                  },
                  {
                      "kills": 0,
                      "item0": 3865,
                      "item2": 0,
                      "role": "UTILITY",
                      "item1": 2003,
                      "csPerMin": 0,
                      "multikill": "None",
                      "champLevel": 1,
                      "assists": 0,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8200,
                      "win": false,
                      "deaths": 1,
                      "damageDealt": 295,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 53,
                      "pinkWards": 1,
                      "summonerSpell2": 14,
                      "summonerSpell1": 4,
                      "summonerName": "aKansper BTT",
                      "kda": 0,
                      "cs": 0,
                      "championName": "Blitzcrank",
                      "wardsPlaced": 0,
                      "keystoneRune": 8351,
                      "wardItem": 3340,
                      "item4": 0,
                      "item3": 0,
                      "damageTaken": 947,
                      "item5": 0
                  }
              ]
          },
          "matchData": {
              "gameDurationMinutes": 1,
              "gameType": "MATCHED_GAME",
              "gameDurationSeconds": 50,
              "gameMode": "CLASSIC",
              "totalGameDuration": 110
          },
          "redTeam": {
              "stats": {
                  "inhibitors": 0,
                  "totalKills": 2,
                  "totalGold": 3392,
                  "barons": 0,
                  "voidGrubs": 0,
                  "riftHeralds": 0,
                  "win": true,
                  "searchedPlayer": false,
                  "dragons": 0,
                  "atakhan": 0,
                  "towers": 0
              },
              "participants": [
                  {
                      "kills": 0,
                      "item0": 2003,
                      "item2": 0,
                      "role": "TOP",
                      "item1": 1054,
                      "csPerMin": 0,
                      "multikill": "None",
                      "champLevel": 1,
                      "assists": 0,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8000,
                      "win": true,
                      "deaths": 0,
                      "damageDealt": 0,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 78,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 12,
                      "summonerName": "Yordle 1 Trick",
                      "kda": 999,
                      "cs": 0,
                      "championName": "Poppy",
                      "wardsPlaced": 0,
                      "keystoneRune": 8437,
                      "wardItem": 3340,
                      "item4": 0,
                      "item3": 0,
                      "damageTaken": 0,
                      "item5": 0
                  },
                  {
                      "kills": 0,
                      "item0": 1102,
                      "item2": 0,
                      "role": "JUNGLE",
                      "item1": 0,
                      "csPerMin": 0,
                      "multikill": "None",
                      "champLevel": 1,
                      "assists": 0,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8300,
                      "win": true,
                      "deaths": 0,
                      "damageDealt": 0,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 120,
                      "pinkWards": 0,
                      "summonerSpell2": 11,
                      "summonerSpell1": 6,
                      "summonerName": "Salt Trucks",
                      "kda": 999,
                      "cs": 0,
                      "championName": "Hecarim",
                      "wardsPlaced": 1,
                      "keystoneRune": 8010,
                      "wardItem": 3364,
                      "item4": 0,
                      "item3": 0,
                      "damageTaken": 549,
                      "item5": 0
                  },
                  {
                      "kills": 0,
                      "item0": 1056,
                      "item2": 0,
                      "role": "MIDDLE",
                      "item1": 2003,
                      "csPerMin": 2.2,
                      "multikill": "None",
                      "champLevel": 1,
                      "assists": 0,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8000,
                      "win": true,
                      "deaths": 0,
                      "damageDealt": 0,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 45,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 12,
                      "summonerName": "breyus",
                      "kda": 999,
                      "cs": 4,
                      "championName": "Veigar",
                      "wardsPlaced": 1,
                      "keystoneRune": 8229,
                      "wardItem": 3340,
                      "item4": 0,
                      "item3": 0,
                      "damageTaken": 0,
                      "item5": 0
                  },
                  {
                      "kills": 1,
                      "item0": 1055,
                      "item2": 0,
                      "role": "BOTTOM",
                      "item1": 2003,
                      "csPerMin": 0,
                      "multikill": "None",
                      "champLevel": 1,
                      "assists": 0,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8300,
                      "win": true,
                      "deaths": 0,
                      "damageDealt": 273,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 81,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 21,
                      "summonerName": "FlevoLuxon",
                      "kda": 999,
                      "cs": 0,
                      "championName": "Ezreal",
                      "wardsPlaced": 0,
                      "keystoneRune": 8008,
                      "wardItem": 3340,
                      "item4": 0,
                      "item3": 0,
                      "damageTaken": 497,
                      "item5": 0
                  },
                  {
                      "kills": 1,
                      "item0": 3865,
                      "item2": 0,
                      "role": "UTILITY",
                      "item1": 2003,
                      "csPerMin": 0,
                      "multikill": "None",
                      "champLevel": 1,
                      "assists": 1,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8100,
                      "win": true,
                      "deaths": 0,
                      "damageDealt": 262,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 44,
                      "pinkWards": 0,
                      "summonerSpell2": 14,
                      "summonerSpell1": 4,
                      "summonerName": "OBman",
                      "kda": 999,
                      "cs": 0,
                      "championName": "Taric",
                      "wardsPlaced": 1,
                      "keystoneRune": 8465,
                      "wardItem": 3340,
                      "item4": 0,
                      "item3": 0,
                      "damageTaken": 263,
                      "item5": 0
                  }
              ]
          }
      },
      {
          "blueTeam": {
              "stats": {
                  "inhibitors": 3,
                  "totalKills": 47,
                  "totalGold": 61266,
                  "barons": 0,
                  "voidGrubs": 3,
                  "riftHeralds": 1,
                  "win": true,
                  "searchedPlayer": true,
                  "dragons": 2,
                  "atakhan": 1,
                  "towers": 11
              },
              "participants": [
                  {
                      "kills": 19,
                      "item0": 1054,
                      "item2": 3071,
                      "role": "MIDDLE",
                      "item1": 3174,
                      "csPerMin": 4.7,
                      "multikill": "Double Kill",
                      "champLevel": 15,
                      "assists": 11,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8200,
                      "win": true,
                      "deaths": 4,
                      "damageDealt": 32628,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 80,
                      "pinkWards": 4,
                      "summonerSpell2": 14,
                      "summonerSpell1": 4,
                      "summonerName": "Triee",
                      "kda": 7.5,
                      "cs": 118,
                      "championName": "Pantheon",
                      "wardsPlaced": 12,
                      "keystoneRune": 8005,
                      "wardItem": 3340,
                      "item4": 3053,
                      "item3": 6610,
                      "damageTaken": 23003,
                      "item5": 1029
                  },
                  {
                      "kills": 6,
                      "item0": 3748,
                      "item2": 3153,
                      "role": "JUNGLE",
                      "item1": 0,
                      "csPerMin": 5.6,
                      "multikill": "None",
                      "champLevel": 15,
                      "assists": 15,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8100,
                      "win": true,
                      "deaths": 7,
                      "damageDealt": 18248,
                      "searchedPlayer": true,
                      "wardsKilled": 2,
                      "championID": 19,
                      "pinkWards": 0,
                      "summonerSpell2": 11,
                      "summonerSpell1": 6,
                      "summonerName": "Anc702",
                      "kda": 3,
                      "cs": 141,
                      "championName": "Warwick",
                      "wardsPlaced": 0,
                      "keystoneRune": 8005,
                      "wardItem": 3364,
                      "item4": 3047,
                      "item3": 0,
                      "damageTaken": 39376,
                      "item5": 3211
                  },
                  {
                      "kills": 12,
                      "item0": 1055,
                      "item2": 3153,
                      "role": "TOP",
                      "item1": 3006,
                      "csPerMin": 9.8,
                      "multikill": "Double Kill",
                      "champLevel": 17,
                      "assists": 3,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8400,
                      "win": true,
                      "deaths": 2,
                      "damageDealt": 26849,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 157,
                      "pinkWards": 1,
                      "summonerSpell2": 14,
                      "summonerSpell1": 4,
                      "summonerName": "AFluffyDemon",
                      "kda": 7.5,
                      "cs": 244,
                      "championName": "Yasuo",
                      "wardsPlaced": 9,
                      "keystoneRune": 8008,
                      "wardItem": 3340,
                      "item4": 3031,
                      "item3": 6673,
                      "damageTaken": 23098,
                      "item5": 1053
                  },
                  {
                      "kills": 7,
                      "item0": 3508,
                      "item2": 3161,
                      "role": "BOTTOM",
                      "item1": 3047,
                      "csPerMin": 9.9,
                      "multikill": "None",
                      "champLevel": 15,
                      "assists": 11,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8300,
                      "win": true,
                      "deaths": 2,
                      "damageDealt": 30012,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 901,
                      "pinkWards": 0,
                      "summonerSpell2": 21,
                      "summonerSpell1": 4,
                      "summonerName": "OCB KingSize",
                      "kda": 9,
                      "cs": 248,
                      "championName": "Smolder",
                      "wardsPlaced": 5,
                      "keystoneRune": 8021,
                      "wardItem": 3363,
                      "item4": 0,
                      "item3": 3031,
                      "damageTaken": 18495,
                      "item5": 1055
                  },
                  {
                      "kills": 3,
                      "item0": 3876,
                      "item2": 3050,
                      "role": "UTILITY",
                      "item1": 3158,
                      "csPerMin": 0.8,
                      "multikill": "None",
                      "champLevel": 13,
                      "assists": 21,
                      "killParticipation": 0,
                      "teamID": 100,
                      "secondaryTree": 8100,
                      "win": true,
                      "deaths": 7,
                      "damageDealt": 9797,
                      "searchedPlayer": false,
                      "wardsKilled": 5,
                      "championID": 497,
                      "pinkWards": 1,
                      "summonerSpell2": 4,
                      "summonerSpell1": 7,
                      "summonerName": "xepax",
                      "kda": 3.43,
                      "cs": 21,
                      "championName": "Rakan",
                      "wardsPlaced": 16,
                      "keystoneRune": 8465,
                      "wardItem": 3364,
                      "item4": 3067,
                      "item3": 3107,
                      "damageTaken": 22285,
                      "item5": 3114
                  }
              ]
          },
          "matchData": {
              "gameDurationMinutes": 24,
              "gameType": "MATCHED_GAME",
              "gameDurationSeconds": 58,
              "gameMode": "CLASSIC",
              "totalGameDuration": 1498
          },
          "redTeam": {
              "stats": {
                  "inhibitors": 0,
                  "totalKills": 22,
                  "totalGold": 45611,
                  "barons": 0,
                  "voidGrubs": 0,
                  "riftHeralds": 0,
                  "win": false,
                  "searchedPlayer": false,
                  "dragons": 1,
                  "atakhan": 0,
                  "towers": 1
              },
              "participants": [
                  {
                      "kills": 4,
                      "item0": 1056,
                      "item2": 3047,
                      "role": "TOP",
                      "item1": 6657,
                      "csPerMin": 5.5,
                      "multikill": "None",
                      "champLevel": 15,
                      "assists": 4,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8000,
                      "win": false,
                      "deaths": 8,
                      "damageDealt": 16706,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 518,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 12,
                      "summonerName": "fryguyfern",
                      "kda": 1,
                      "cs": 137,
                      "championName": "Neeko",
                      "wardsPlaced": 6,
                      "keystoneRune": 8437,
                      "wardItem": 3340,
                      "item4": 1029,
                      "item3": 3165,
                      "damageTaken": 27530,
                      "item5": 0
                  },
                  {
                      "kills": 11,
                      "item0": 3142,
                      "item2": 6697,
                      "role": "JUNGLE",
                      "item1": 3133,
                      "csPerMin": 5.4,
                      "multikill": "Triple Kill",
                      "champLevel": 13,
                      "assists": 3,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8300,
                      "win": false,
                      "deaths": 11,
                      "damageDealt": 24365,
                      "searchedPlayer": false,
                      "wardsKilled": 4,
                      "championID": 91,
                      "pinkWards": 0,
                      "summonerSpell2": 11,
                      "summonerSpell1": 14,
                      "summonerName": "krypt",
                      "kda": 1.27,
                      "cs": 135,
                      "championName": "Talon",
                      "wardsPlaced": 0,
                      "keystoneRune": 8021,
                      "wardItem": 3364,
                      "item4": 3071,
                      "item3": 3158,
                      "damageTaken": 39243,
                      "item5": 2019
                  },
                  {
                      "kills": 3,
                      "item0": 1055,
                      "item2": 1036,
                      "role": "MIDDLE",
                      "item1": 0,
                      "csPerMin": 4.6,
                      "multikill": "None",
                      "champLevel": 13,
                      "assists": 8,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8400,
                      "win": false,
                      "deaths": 13,
                      "damageDealt": 20268,
                      "searchedPlayer": false,
                      "wardsKilled": 2,
                      "championID": 150,
                      "pinkWards": 0,
                      "summonerSpell2": 4,
                      "summonerSpell1": 14,
                      "summonerName": "PSYCHO",
                      "kda": 0.85,
                      "cs": 114,
                      "championName": "Gnar",
                      "wardsPlaced": 5,
                      "keystoneRune": 8005,
                      "wardItem": 3340,
                      "item4": 3047,
                      "item3": 3053,
                      "damageTaken": 31002,
                      "item5": 3078
                  },
                  {
                      "kills": 2,
                      "item0": 1055,
                      "item2": 3124,
                      "role": "BOTTOM",
                      "item1": 6672,
                      "csPerMin": 6.6,
                      "multikill": "None",
                      "champLevel": 13,
                      "assists": 3,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8400,
                      "win": false,
                      "deaths": 7,
                      "damageDealt": 10595,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 67,
                      "pinkWards": 0,
                      "summonerSpell2": 21,
                      "summonerSpell1": 4,
                      "summonerName": "DarkWikdo",
                      "kda": 0.71,
                      "cs": 164,
                      "championName": "Vayne",
                      "wardsPlaced": 7,
                      "keystoneRune": 8008,
                      "wardItem": 3340,
                      "item4": 3006,
                      "item3": 0,
                      "damageTaken": 19361,
                      "item5": 0
                  },
                  {
                      "kills": 2,
                      "item0": 3877,
                      "item2": 1028,
                      "role": "UTILITY",
                      "item1": 1036,
                      "csPerMin": 1.8,
                      "multikill": "None",
                      "champLevel": 12,
                      "assists": 6,
                      "killParticipation": 0,
                      "teamID": 200,
                      "secondaryTree": 8400,
                      "win": false,
                      "deaths": 8,
                      "damageDealt": 10885,
                      "searchedPlayer": false,
                      "wardsKilled": 0,
                      "championID": 164,
                      "pinkWards": 0,
                      "summonerSpell2": 14,
                      "summonerSpell1": 4,
                      "summonerName": "Vhχ",
                      "kda": 1,
                      "cs": 45,
                      "championName": "Camille",
                      "wardsPlaced": 12,
                      "keystoneRune": 9923,
                      "wardItem": 3364,
                      "item4": 3009,
                      "item3": 6692,
                      "damageTaken": 22283,
                      "item5": 0
                  }
              ]
          }
      }
  ],
  "rank": "IV",
  "gameName": "Anc702",
  "losses": 92,
  "name_tag": "Anc702#NA1",
  "region": "americas",
  "puuid": "74TzNspqk7h_TPPfAGrzfolSgkmUetzLsM80gI-schcpnrM4WJ5awLql6iHYuXSf82rb1kDW08XDdg",
  "wins": 105
}

export default function DocsPage() {
  return (
    <div>
      <ProfileHeader summonerInfo={summonerInfo} />
      <div className="flex flex-col gap-2 md:flex-row">
        <aside className="flex flex-col gap-2 md:w-[332px] md:basis-[332px]">
          <RankedDisplay summonerInfo={summonerInfo} />
        </aside>
        <main className="flex flex-1 flex-col gap-2">
          <Card className="flex flex-col gap-[8px] md:max-w-[740px]">
            {/* Loop through matches and render MatchDisplay for each */}
            {summonerInfo.matches.map((match: any, index: number) => (
              <MatchDisplay key={index} matchInfo={match} />
            ))}
          </Card>
        </main>
      </div>
    </div>
  );
}